import Head from 'next/head'
import homePageStyles from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={homePageStyles.homePage}>
        <div className={homePageStyles.title}>Hello, there 1</div>
      </main>
    </>
  )
}
